name: PHPStan
on:
  pull_request:
  push:
    branches:
      - 'refs/pull/*'
      - 'main'

env:
  CI: true

jobs:
  run:
    name: PHPStan ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.1' ]

    steps:
      -   name: Checkout
          uses: actions/checkout@v5

      -   name: Install PHP
          uses: shivammathur/setup-php@v2
          with:
            coverage: none
            php-version: ${{ matrix.php }}
            ini-values: memory_limit=-1
            tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      -   name: PHPStan
          run: ./vendor/bin/phpstan analyse
